const react = require('eslint-plugin-react');
const globals = require('globals');

module.exports = [
  {
    files: ['src/**/*.{js,jsx,mjs,cjs}'],
    plugins: {
      react,
    },
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      'react/jsx-uses-react': 'error',
      'react/jsx-uses-vars': 'error',
      'callback-return': 'warn',
      'camelcase': 'warn',
      'consistent-return': 'off',
      'constructor-super': 'warn',
      'curly': 'error',
      'dot-notation': 'warn',
      'eqeqeq': 'warn',
      'func-names': 'off',
      'handle-callback-err': 'warn',
      'init-declarations': ['warn', 'always'],
      'max-nested-callbacks': ['error', { max: 4 }],
      'max-params': ['error', { max: 5 }],
      'new-cap': 'error',
      'new-parens': 'warn',
      'no-alert': 'error',
      'no-array-constructor': 'error',
      'no-caller': 'warn',
      'no-class-assign': 'error',
      'no-cond-assign': ['warn', 'except-parens'],
      'no-console': 'error',
      'no-const-assign': 'error',
      'no-constant-condition': 'warn',
      'no-debugger': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-duplicate-imports': 'error',
      'no-empty-pattern': 'error',
      'no-empty': 'error',
      'no-ex-assign': 'error',
      'no-extra-bind': 'error',
      'no-extra-parens': 'off',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-implied-eval': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'warn',
      'no-labels': ['error', { allowLoop: true, allowSwitch: true }],
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-native-reassign': 'error',
      'no-nested-ternary': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-symbol': 'error',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'error',
      'no-path-concat': 'error',
      'no-proto': 'warn',
      'no-return-await': 'error',
      'no-self-assign': 'error',
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'error',
      'no-shadow': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-undef': 'error',
      'no-unneeded-ternary': 'error',
      'no-unreachable': 'error',
      'no-unused-expressions': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',
      'no-with': 'error',
      'object-shorthand': ['warn', 'always'],
      'prefer-const': 'error',
      'radix': 'error',
      'require-await': 'error',
      'semi': 'error',
      'space-infix-ops': ['warn', { int32Hint: false }],
      'space-unary-ops': ['warn', { words: true, nonwords: false }],
      'strict': ['error', 'never'],
      'use-isnan': 'error',
      'prefer-destructuring': 'warn',
    },
  },
];
